### ISSUE TITLE
After I deploy That ripo I got this error.

### ISSUE THREAD

**Issue by sushen** [tippexs/unitwp#2]
![Issue](https://user-images.githubusercontent.com/4492335/73852855-17191e00-485a-11ea-87ee-74355c67b332.png)

and My exposed IP I got nothing.

I frog this repo put my wordpress file in the wordpress folder then I trigger this repo and got this error.

**Comment by tippexs** [comment]
Please provide the log output of the crashed pod / container. To do so use the kubectl or the k8s dashboard.

**Comment by sushen** [comment]
> Please provide the log output of the crashed pod / container. To do so use the kubectl or the k8s dashboard.

That is the log link and it's successfully done . Buy problem is in Next steap.

https://00e9e64bac72b0c7f220297d6c037b6d868dbaa70aa8fe4a85-apidata.googleusercontent.com/download/storage/v1/b/497806420977.cloudbuild-logs.googleusercontent.com/o/log-cfb8b954-5c87-4d1b-96f9-2628b2e414f3.txt?qk=AD5uMEvjYtMsD2Bv-OlAP-cUSJUKyT8fkZPzowG8nvJr1EWUttRxb6WdD6D40BBMoVHONKhHZpTrV8x8zGwYviJPDb-bvGPHPxABimVoyKl4yD-r3eU8bFOlWjl8qLPVqKl_uF3Cbe3HPjTy_qeRi8Dhd0b79l7MVmCKarRL1MAMfbpQqJ6s0knxvnCygIfiVetqq3Sijk0m_OJAtdVWoJnfv8HXi_SBljbnyhNmQ-lzIM8Czb2qPPKuYJrLmkHo9xKy-QT0GAaiXgDmfv3DLSmuFg9Q9XxSIP2fdQnakvh3KX0vh4GxDsS4s68Xd0XxrZUUHngIvRNHdbDP9lUygS5J3UjHbD9WjOWbgO-xLOrMhxoQTDEOu_9VHij_mqA0s_Eo1WTdMGv10P5wMxmsx5C5AItvesU0X_PBzynvMXq6mxZbyGuRmVmwy9s_wtRDGgUFUmIslSdvM-_TbOkNqwl1GAd9KPphHVwDN3U25FTkWowdP8HKj8LOqOL6AQueYyw3gZFO8gA_wpId9AnpFNeQGaB0oKJCtG5XQ8ynQVNj33BeGqLXVV-bdWYot9e4Er6PlRp4Uc7iBGx5A9pRZ-391xY75kIKHw2lB9lo5mPV4jHm1l4ziqwSs7YC0Fp_aG15otwdZhgGSWBdtTH1yS_R7wyp-mt36VF8SlnqkgfxVzlfKNPmYtdsLtXtyInNYg3vH0s22l5VGt-je6Uf51aZIvVUoddJzan92Va4DKlC6zmcuxGaoMWhTm3ZWS0fQbpnxpNVDxXlF1XyTZbs-fOOOupFaxon-QYaIwbqOFJkh5LOCDyx8QtZqQlaHxwFiG-kcX5usBdKTWXETyPWZYiTjSRY-My8QE6xayrNVi4Hr0cpggDZ6uv7pU9l3gNcmzeWgvsAt3dA

**Comment by tippexs** [comment]
This is the output of the build step. Looks like to container was build successfully.

1. What is the content of the wordpress folder while building the container?
2. Please run the container locally and see the log: 

in your work dir run `docker build -t my/unitwp .` and `docker run -it my/unitwp:latest`

what is the log output of running the container locally?  I will add a new md-file later today describing the whole local build process.

**Comment by sushen** [comment]
> This is the output of the build step. Looks like to container was build successfully.
> 
> 1. What is the content of the wordpress folder while building the container?
> 2. Please run the container locally and see the log:
> 
> in your work dir run `docker build -t my/unitwp .` and `docker run -it my/unitwp:latest`
> 
> what is the log output of running the container locally? I will add a new md-file later today describing the whole local build process.

Let me do it.

**Comment by sushen** [comment]
> > This is the output of the build step. Looks like to container was build successfully.
> > 
> > 1. What is the content of the wordpress folder while building the container?
> > 2. Please run the container locally and see the log:
> > 
> > in your work dir run `docker build -t my/unitwp .` and `docker run -it my/unitwp:latest`
> > what is the log output of running the container locally? I will add a new md-file later today describing the whole local build process.
> 
> Let me do it.

**Comment by sushen** [comment]
I never run Kubernaties from my local machine , Can it possible to happen from gitrepo.

This the repo I use https://github.com/sushen/unitwp

**Comment by sushen** [comment]
Its work. Thank You a lot.
