### ISSUE TITLE
Can You Guide me to deploy 

### ISSUE THREAD

**Issue by sushen** [tippexs/unitwp#3]
I am fork this repo and put my WordPress file in the WordPress folder and deploy it in a cluster.
My build was successful.
but in my workload, I got the error and I mention it previous issue.

Can you help me to follow a workflow, I don't know where I am missing?

**Comment by tippexs** [comment]
Hi - This repo contains an example configurtation running WP with NGINX Unit and build container. If you have trouble deploying the container please try to find help outside of this repository. Maybe I can provide a Wiki page how to deploy the container into various environments later.
