### ISSUE TITLE
Where I am going to find my credentials for Wordpress Setup

### ISSUE THREAD

**Issue by sushen** [tippexs/unitwp#4]
I can't find my SQL credential. I thought after installing WordPress It will generate wp-config in the traditional way but it didn't work that way. Can you help me to get the direction?

![Wordpress Credentials](https://user-images.githubusercontent.com/4492335/73901742-e539a300-48bd-11ea-8e95-68daaf88aad4.png)

**Comment by tippexs** [comment]
The WP-Installer will create the config for you. That is correct. I would use another approach.

Create a wp-config.php file and specifiy the values for the DB-Connection. 
Please note: DO NOT COMMIT IT TO YOUR GIT REPO!

In general I set my sensitive connection data with environment variables during the deployment. You can use a composer package named `phpdotenv` to read out the envrionment. There are tutorials arround how to do it. Hope that helps.
