### ISSUE TITLE
I can find the sql port and I cant exposse it

### ISSUE THREAD

**Issue by sushen** [tippexs/unitwp#5]
Successful Nginx :
![nginx](https://user-images.githubusercontent.com/4492335/74010839-9caee200-49b0-11ea-9304-d97ba37c84f3.png)

Successful Wordpress :
![Wordpress](https://user-images.githubusercontent.com/4492335/74010851-a1739600-49b0-11ea-9bd7-1d36e2f7c79a.png)

**ButI can't find the My SQL post. Like I expose WordPress in post 8080**.

**Comment by sushen** [comment]
You help me to build a WordPress website and
I am using Google Cloud Platform for hosting our Website.
I am using My SQL Database on our website.
Locally WordPress wp-config creat automatically or we can create it bechouse we have access to the file.
now I cant push a wp-config file to Github.
but it needs a database name, a username, a DB password, and a DB host. 
where I am going to find it Google Cloud.
In the Linux server, we create a SQL database with that information.
In that case where I am going find a similar thing.

**Comment by sushen** [comment]
Someone posted a similar problem.

https://github.com/GoogleCloudPlatform/php-docs-samples/issues/494

**Comment by tippexs** [comment]
As discussed. Issue closed.
